set default value of status input to false + minor readme update
sclorg/testing-farm-as-github-action pull request #78
Opened 2023-01-30 11:41 UTC by zmiklank

The `update_pull_request_status` input is now set to false by default.

This change is not backwards compatible.
Users, who wish to have the status in the PR displayed need to specify
this input explicitly in their yaml configuration file.

Reason for this change is, that there are more possible triggers for
TFaGA than Pull Request and Issue Comment and in those this setting is
not applicable when set to true.

Resolves: https://github.com/sclorg/testing-farm-as-github-action/issues/65

2023-01-30 11:41 UTC, zmiklank commented
[test]

2024-01-18 14:25 UTC, jamacku requested changes
Since you have updated the default settings, you have to update all `expect(mocks.request).toHaveBeenCalledTimes(x)` checks.

```ts
 FAIL  tests/action.test.ts > Integration tests > Minimal
AssertionError: expected "spy" to be called 3 times, but got 1 times
 ❯ tests/action.test.ts:221:27
    219| 
    220|     // First call to request PR details, next two calls for setting th…
    221|     expect(mocks.request).toHaveBeenCalledTimes(3);
       |                           ^
    222|     expect(mocks.request).toHaveBeenLastCalledWith(
    223|       'POST /repos/{owner}/{repo}/statuses/{sha}',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/6]⎯

 FAIL  tests/action.test.ts > Integration tests > Failed test
AssertionError: expected "spy" to be called 3 times, but got 1 times
 ❯ tests/action.test.ts:302:27
    300| 
    301|     // First call to request PR details, next two calls for setting th…
    302|     expect(mocks.request).toHaveBeenCalledTimes(3);
       |                           ^
    303|     expect(mocks.request).toHaveBeenLastCalledWith(
    304|       'POST /repos/{owner}/{repo}/statuses/{sha}',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/6]⎯

 FAIL  tests/action.test.ts > Integration tests > Testing Farm infrastructure error
AssertionError: expected "spy" to be called 3 times, but got 1 times
 ❯ tests/action.test.ts:381:27
    379| 
    380|     // First call to request PR details, next two calls for setting th…
    381|     expect(mocks.request).toHaveBeenCalledTimes(3);
       |                           ^
    382|     expect(mocks.request).toHaveBeenLastCalledWith(
    383|       'POST /repos/{owner}/{repo}/statuses/{sha}',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[3/6]⎯

 FAIL  tests/action.test.ts > Integration tests > Testing Farm request details timeout
AssertionError: expected "spy" to be called 2 times, but got 1 times
 ❯ tests/action.test.ts:460:27
    458|     // First call to request PR details, next call for setting the sta…
    459|     // TODO: Check if we set the status to error (it's done in main.ts)
    460|     expect(mocks.request).toHaveBeenCalledTimes(2);
       |                           ^
    461| 
    462|     // Test summary

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[4/6]⎯

 FAIL  tests/action.test.ts > Integration tests > Testing Farm private scope
AssertionError: expected "spy" to be called 3 times, but got 1 times
 ❯ tests/action.test.ts:519:27
    517| 
    518|     // First call to request PR details, next two calls for setting th…
    519|     expect(mocks.request).toHaveBeenCalledTimes(3);
       |                           ^
    520|     expect(mocks.request).toHaveBeenLastCalledWith(
    521|       'POST /repos/{owner}/{repo}/statuses/{sha}',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[5/6]⎯

 FAIL  tests/action.test.ts > Integration tests > Pull Request comment with results
AssertionError: expected "spy" to be called 4 times, but got 2 times
 ❯ tests/action.test.ts:593:27
    591| 
    592|     // First call to request PR details, next two calls for setting th…
    593|     expect(mocks.request).toHaveBeenCalledTimes(4);
 Test Files  1 failed | 4 passed (5)
       |                           ^
    594|     expect(mocks.request).toHaveBeenCalledWith(
    595|       'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[6/6]⎯
```

2024-01-23 08:52 UTC, zmiklank commented
This PR now removes the `pr_head_sha` input as it is no longer needed. The information provided by this input is now gathered directly from GitHub metadata.

2024-01-23 08:57 UTC, jamacku approved these changes

2024-01-23 08:59 UTC, merged